### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by AysKrimn** [RythmTechnologies/animated-octo-winner#72]
Error: ModuleNotFoundError: No module named 'xhtml2pdf' when i launch app. Perhaps  the module is not in required files

Full message:
```
django-archaeology-1  | Watching for file changes with StatReloader
django-archaeology-1  | Performing system checks...
django-archaeology-1  |
django-archaeology-1  | Exception in thread django-main-thread:
django-archaeology-1  | Traceback (most recent call last):
django-archaeology-1  |   File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
django-archaeology-1  |     self.run()
django-archaeology-1  |   File "/usr/local/lib/python3.12/threading.py", line 1010, in run
django-archaeology-1  |     self._target(*self._args, **self._kwargs)
django-archaeology-1  |   File "/usr/local/lib/python3.12/site-packages/django/utils/autoreload.py", line 64, in wrapper
django-archaeology-1  |     fn(*args, **kwargs)
django-archaeology-1  |   File "/usr/local/lib/python3.12/site-packages/django/core/management/commands/runserver.py", line 133, in inner_run
django-archaeology-1  |     self.check(display_num_errors=True)
django-archaeology-1  |   File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 485, in check
django-archaeology-1  |     all_issues = checks.run_checks(
django-archaeology-1  |                  ^^^^^^^^^^^^^^^^^^
django-archaeology-1  |   File "/usr/local/lib/python3.12/site-packages/django/core/checks/registry.py", line 88, in run_checks
django-archaeology-1  |     new_errors = check(app_configs=app_configs, databases=databases)
django-archaeology-1  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-archaeology-1  |   File "/usr/local/lib/python3.12/site-packages/django/core/checks/urls.py", line 42, in check_url_namespaces_unique
django-archaeology-1  |     all_namespaces = _load_all_namespaces(resolver)
django-archaeology-1  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-archaeology-1  |   File "/usr/local/lib/python3.12/site-packages/django/core/checks/urls.py", line 61, in _load_all_namespaces
django-archaeology-1  |     url_patterns = getattr(resolver, "url_patterns", [])
django-archaeology-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-archaeology-1  |   File "/usr/local/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
django-archaeology-1  |     res = instance.__dict__[self.name] = self.func(instance)
django-archaeology-1  |                                          ^^^^^^^^^^^^^^^^^^^
django-archaeology-1  |   File "/usr/local/lib/python3.12/site-packages/django/urls/resolvers.py", line 735, in url_patterns
django-archaeology-1  |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
django-archaeology-1  |                        ^^^^^^^^^^^^^^^^^^^
django-archaeology-1  |   File "/usr/local/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
django-archaeology-1  |     res = instance.__dict__[self.name] = self.func(instance)
django-archaeology-1  |                                          ^^^^^^^^^^^^^^^^^^^
django-archaeology-1  |   File "/usr/local/lib/python3.12/site-packages/django/urls/resolvers.py", line 728, in urlconf_module
django-archaeology-1  |     return import_module(self.urlconf_name)
django-archaeology-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-archaeology-1  |   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
django-archaeology-1  |     return _bootstrap._gcd_import(name[level:], package, level)
django-archaeology-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-archaeology-1  |   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
django-archaeology-1  |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
django-archaeology-1  |   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
django-archaeology-1  |   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
django-archaeology-1  |   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
django-archaeology-1  |   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
django-archaeology-1  |   File "/home/archaeology/archaeologyMain/urls.py", line 23, in <module>
django-archaeology-1  |     from apps.document.views import *
django-archaeology-1  |   File "/home/archaeology/apps/document/views.py", line 10, in <module>
django-archaeology-1  |     from xhtml2pdf import pisa
django-archaeology-1  | ModuleNotFoundError: No module named 'xhtml2pdf'
```

**Comment by AysKrimn** [comment]
I updated required files manually
